### ISSUE TITLE
Добавить дату покупки

### ISSUE THREAD

**Issue by dnandrv** [yangirov/wesplit#40]
Хочется иметь возможность в больших поездках указывать дату покупки чтобы не путаться. Видеть дату покупки на листе события. Внутри события покупки отсортированы desc

**Comment by yangirov** [comment]
✅  И добавил фильтр по дате/сумме по убыванию/возрастанию

![image](https://github.com/user-attachments/assets/189fc8c8-029e-4393-8d9c-7d6fde2f9b6d)
